In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('500hits.csv' , encoding= 'latin-1')

In [3]:
df.head()

         PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB   CS     BA  HOF
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   357  892  178  0.366    1
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   696   78   31  0.331    1
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   220  432  129  0.345    1
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358   97  0.310    1
4  Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   327  722   15  0.329    1

In [4]:
X = df.drop(columns=['PLAYER', 'HOF'])

In [5]:
y = df['HOF']

In [9]:
X.shape

(465, 14)

In [10]:
y.shape

(465,)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=11, test_size=0.2)

In [12]:
X_train.shape

(372, 14)

In [13]:
X_test.shape

(93, 14)

In [14]:
y_train.shape

(372,)

In [15]:
y_test.shape

(93,)

In [16]:
X_train.head()

     YRS     G    AB     R     H   2B   3B   HR   RBI    BB    SO   SB   CS     BA
289   18  2028  7298   873  1993  284   40  325  1163   620  1313   20   38  0.273
288   13  1836  6826   856  1996  392  117   43   402   513   360  247  108  0.292
350   14  1799  6373   876  1854  282   64   49   630   844   627   37   51  0.291
196   17  2158  7911  1057  2276  414   92   94   844   690   784  246  138  0.288
184   19  2390  8570  1386  2369  420   65  244  1084  1197  1099  143   75  0.276

In [17]:
y_train.head()

289    0
288    0
350    0
196    0
184    0
Name: HOF, dtype: int64

In [19]:
X_train.describe()

              YRS            G            AB            R  ...           SO           SB          CS          BA
count  372.000000   372.000000    372.000000   372.000000  ...   372.000000   372.000000  372.000000  372.000000
mean    17.010753  2046.521505   7526.077957  1154.126344  ...   850.322581   196.927419   58.986559    0.289164
std      2.662486   351.232903   1302.405807   291.308439  ...   472.917969   185.585713   49.322224    0.021069
min     11.000000  1331.000000   4981.000000   651.000000  ...     0.000000     7.000000    0.000000    0.246000
25%     15.000000  1797.500000   6507.500000   936.000000  ...   448.000000    64.500000   23.000000    0.274000
50%     17.000000  1992.000000   7237.000000  1099.000000  ...   844.000000   141.000000   52.000000    0.288000
75%     19.000000  2245.500000   8198.250000  1305.000000  ...  1234.250000   285.500000   84.000000    0.300250
max     26.000000  3308.000000  12364.000000  2295.000000  ...  1936.000000  1406.000000  335.000000    0.366000

[8 rows x 14 columns]

In [20]:
X_train.describe().round(3)

           YRS         G         AB         R         H  ...        BB        SO        SB       CS       BA
count  372.000   372.000    372.000   372.000   372.000  ...   372.000   372.000   372.000  372.000  372.000
mean    17.011  2046.522   7526.078  1154.126  2177.995  ...   780.105   850.323   196.927   58.987    0.289
std      2.662   351.233   1302.406   291.308   426.615  ...   327.453   472.918   185.586   49.322    0.021
min     11.000  1331.000   4981.000   651.000  1660.000  ...   239.000     0.000     7.000    0.000    0.246
25%     15.000  1797.500   6507.500   936.000  1838.000  ...   536.500   448.000    64.500   23.000    0.274
50%     17.000  1992.000   7237.000  1099.000  2080.500  ...   719.000   844.000   141.000   52.000    0.288
75%     19.000  2245.500   8198.250  1305.000  2383.750  ...   961.250  1234.250   285.500   84.000    0.300
max     26.000  3308.000  12364.000  2295.000  4189.000  ...  2190.000  1936.000  1406.000  335.000    0.366

[8 rows x 14 columns]

In [21]:
X_test.describe().round(3)

          YRS         G         AB         R         H       2B  ...       RBI        BB        SO       SB       CS      BA
count  93.000    93.000     93.000    93.000    93.000   93.000  ...    93.000    93.000    93.000   93.000   93.000  93.000
mean   17.204  2057.409   7452.968  1135.065  2139.258  374.742  ...   867.011   797.387   836.065  191.817   54.473   0.287
std     3.154   368.580   1265.371   283.877   415.165   93.929  ...   495.127   328.755   552.309  166.926   42.508   0.022
min    11.000  1399.000   5472.000   601.000  1660.000  206.000  ...     0.000   266.000    15.000    8.000    0.000   0.248
25%    15.000  1820.000   6622.000   935.000  1818.000  310.000  ...   618.000   527.000   359.000   61.000   15.000   0.272
50%    17.000  1997.000   7359.000  1108.000  2054.000  361.000  ...   926.000   750.000   745.000  137.000   50.000   0.285
75%    19.000  2282.000   8096.000  1283.000  2256.000  432.000  ...  1138.000   937.000  1179.000  271.000   83.000   0.299
max    25.000  2850.000  10876.000  1859.000  3430.000  668.000  ...  1922.000  1747.000  2597.000  744.000  173.000   0.340

[8 rows x 14 columns]